name: Validate HTML

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install tidy
      run: sudo apt-get install -y tidy
    - name: Validate HTML
      run: tidy -q -e index.html